services:
  frontend:
    build:
      context: ./src/main/vue/fuzzyweb
    container_name: vue-frontend
    environment:
      - VITE_BACKEND_API_URL=http://localhost:8080/api
    expose:
      - "8080"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    container_name: java-backend
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
